pipeline:
  seed: 42

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}
  bwd_langpair: ${.tgt_lang}-${.src_lang}

  pipeline_dir: experiments/${.langpair}/pipeline.bidirectional.resources
  data_root_dir: data/${.langpair}

  vocab_size: 64000
  marian_dir: marian
  marian_config: config/marian.train.teacher.base.yml
  opustrainer_config: null
  max_epochs: null
  valid_dataset: flores200.dev.${.langpair}
  train_categories: ["clean"]
  train_category_ratios: [1.0]

  steps:
    # Load Datasets
    - step: raw
      step_label: train.${...langpair}
      raw_data_dir: ${...data_root_dir}/raw/v0

    - step: raw
      step_label: valid.${...langpair}
      raw_data_dir: ${...data_root_dir}/valid
      compressed: False

    - step: raw
      step_label: test.${...langpair}
      raw_data_dir: ${...data_root_dir}/test
      compressed: False

    # Train FWD
    - step: generate_vocab
      step_label: generate_vocab.${...langpair}
      corpus_step: train.${...langpair}
      runner_resources:
        mem: 50g
        cpus: 8

    - step: train_model
      step_label: train_model.${...langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: train.${...langpair}
      valid_corpus_step: valid.${...langpair}
      runner_resources:
        mem: 20g
        gpus: 2

    # Train BWD
    - step: train_model
      step_label: train_model.${...bwd_langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: train.${...langpair}
      valid_corpus_step: valid.${...langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        mem: 20g
        gpus: 2

    # Evaluation FWD
    - step: translate
      step_label: translate_test.${...langpair}
      prev_corpus_step: test.${...langpair}
      model_step: train_model.${...langpair}
      runner_resources:
        gpus: 1
        mem: 10g

    - step: evaluate
      step_label: evaluate_test.${...langpair}
      translated_corpus_step: translate_test.${...langpair}
      reference_corpus_step: test.${...langpair}

    # Evaluation BWD
    - step: translate
      step_label: translate_test.${...bwd_langpair}
      prev_corpus_step: test.${...langpair}
      model_step: train_model.${...bwd_langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        gpus: 1
        mem: 10g

    - step: evaluate
      step_label: evaluate_test.${...bwd_langpair}
      translated_corpus_step: translate_test.${...bwd_langpair}
      reference_corpus_step: test.${...langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}


  targets:
    - evaluate_test.${..langpair}
    - evaluate_test.${..bwd_langpair}

runner:
  runner: slurm
  slurm_time: "0:30:00"
  runner_resources:
    mem: 10g
    cpus: 4
