pipeline:
  seed: 42

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}
  bwd_langpair: ${.tgt_lang}-${.src_lang}

  pipeline_dir: experiments/${.langpair}/pipeline.backtranslation
  data_root_dir: experiments/${.langpair}/pipeline.data_preprocess/

  # Vocabulary and Model training globals
  vocab_size: 64000
  marian_dir: marian
  marian_config: config/marian.train.teacher.base.yml

  # Model training globals
  opustrainer_config: null
  max_epochs: null
  valid_dataset: flores200.dev.${.langpair}
  train_categories: ["clean"]
  train_category_ratios: [1.0]

  # Backtranslation Model training globals
  bt_train_categories: ["organic.clean", "synthetic.clean"]
  bt_train_category_ratios: [0.8, 0.2]

  # Corpus Merge step globals
  prev_corpus_label: "organic"
  other_corpus_label: "synthetic"

  steps:
    # Load Datasets
    - step: raw
      step_label: train.${...langpair}
      raw_data_dir: ${...data_root_dir}/gather.${...langpair}/output/

    - step: raw
      step_label: train.${...src_lang}
      raw_data_dir: ${...data_root_dir}/gather.${...src_lang}/output/
      src_lang: ${...src_lang}
      tgt_lang: null

    - step: raw
      step_label: train.${...tgt_lang}
      raw_data_dir: ${...data_root_dir}/gather.${...tgt_lang}/output/
      src_lang: ${...tgt_lang}
      tgt_lang: null

    - step: raw
      step_label: valid.${...langpair}
      raw_data_dir: ${...data_root_dir}/valid.${...langpair}/output/

    - step: raw
      step_label: test.${...langpair}
      raw_data_dir: ${...data_root_dir}/test.${...langpair}/output/


    # Generate vocab
    - step: generate_vocab
      step_label: generate_vocab.${...langpair}
      corpus_step: train.${...langpair}
      runner_resources:
        mem: 50g
        cpus: 8

    # Train FWD
    - step: train_model
      step_label: train_model.${...langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: train.${...langpair}
      valid_corpus_step: valid.${...langpair}
      runner_resources:
        mem: 20g
        gpus: 2

    # Train BWD
    - step: train_model
      step_label: train_model.${...bwd_langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: train.${...langpair}
      valid_corpus_step: valid.${...langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        mem: 20g
        gpus: 2

    # Translate Mono Data
    - step: translate
      step_label: translate.${...langpair}
      prev_corpus_step: train.${...src_lang}
      model_step: train_model.${...langpair}
      runner_resources:
        mem: 10g
        gpus: 1

    - step: translate
      step_label: translate.${...bwd_langpair}
      prev_corpus_step: train.${...tgt_lang}
      model_step: train_model.${...bwd_langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        mem: 10g
        gpus: 1

    # Merge auth and synth data into a single corpus step
    - step: merge
      step_label: merge.${...langpair}
      prev_corpus_step: train.${...langpair}
      other_corpus_step: translate.${...bwd_langpair}

    - step: merge
      step_label: merge.${...bwd_langpair}
      prev_corpus_step: train.${...langpair}
      other_corpus_step: translate.${...langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}

    # Train Backtranslation FWD
    - step: train_model
      step_label: train_model_bt.${...langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: merge.${...langpair}
      valid_corpus_step: valid.${...langpair}
      train_categories: ${...bt_train_categories}
      train_category_ratios: ${...bt_train_category_ratios}
      runner_resources:
        mem: 20g
        gpus: 2

    # Train Backtranslation BWD
    - step: train_model
      step_label: train_model_bt.${...bwd_langpair}
      vocab_step: generate_vocab.${...langpair}
      train_corpus_step: merge.${...bwd_langpair}
      valid_corpus_step: valid.${...langpair}
      train_categories: ${...bt_train_categories}
      train_category_ratios: ${...bt_train_category_ratios}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        mem: 20g
        gpus: 2

    # Eval FWD
    - step: translate
      step_label: translate_test.${...langpair}
      prev_corpus_step: test.${...langpair}
      model_step: train_model_bt.${...langpair}
      runner_resources:
        mem: 20g
        gpus: 1

    - step: evaluate
      step_label: evaluate_test.${...langpair}
      translated_corpus_step: translate_test.${...langpair}
      reference_corpus_step: test.${...langpair}

    # Eval BWD
    - step: translate
      step_label: translate_test.${...bwd_langpair}
      prev_corpus_step: test.${...langpair}
      model_step: train_model_bt.${...bwd_langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}
      runner_resources:
        mem: 20g
        gpus: 1

    - step: evaluate
      step_label: evaluate_test.${...bwd_langpair}
      translated_corpus_step: translate_test.${...bwd_langpair}
      reference_corpus_step: test.${...langpair}
      src_lang: ${...tgt_lang}
      tgt_lang: ${...src_lang}

  targets:
    - evaluate_test.${..langpair}
    - evaluate_test.${..bwd_langpair}

runner:
  runner: slurm
  slurm_time: "48:00:00"
  runner_resources:
    mem: 10g
    cpus: 4
