authors: false
cite: false
build-info: ""
workspace: 25000
log-level: info
log-time-zone: ""
quiet: false
quiet-translation: false
seed: 1111
check-nan: false
interpolate-env-vars: false
relative-paths: false
dump-config: ""
sigterm: save-and-exit
pretrained-model: ""
ignore-model-config: false
type: transformer
dim-vocabs:
  - 64539
  - 64539
dim-emb: 1024
factors-dim-emb: 0
factors-combine: sum
lemma-dependency: ""
lemma-dim-emb: 0
dim-rnn: 1024
enc-type: bidirectional
enc-cell: gru
enc-cell-depth: 1
enc-depth: 12
dec-cell: gru
dec-cell-base-depth: 2
dec-cell-high-depth: 1
dec-depth: 6
skip: false
layer-normalization: false
right-left: false
input-types: []
tied-embeddings: false
tied-embeddings-src: false
tied-embeddings-all: true
output-omit-bias: false
transformer-heads: 16
transformer-no-projection: false
transformer-rnn-projection: false
transformer-pool: false
transformer-dim-ffn: 4096
transformer-decoder-dim-ffn: 0
transformer-ffn-depth: 2
transformer-decoder-ffn-depth: 0
transformer-ffn-activation: swish
transformer-dim-aan: 2048
transformer-aan-depth: 2
transformer-aan-activation: swish
transformer-aan-nogate: false
transformer-decoder-autoreg: self-attention
transformer-tied-layers: []
transformer-guided-alignment-layer: last
transformer-preprocess: ""
transformer-postprocess-emb: d
transformer-postprocess: dan
transformer-postprocess-top: ""
transformer-train-position-embeddings: false
transformer-depth-scaling: false
bert-mask-symbol: "[MASK]"
bert-sep-symbol: "[SEP]"
bert-class-symbol: "[CLS]"
bert-masking-fraction: 0.15
bert-train-type-embeddings: true
bert-type-vocab-size: 2
char-stride: 5
char-highway: 4
char-conv-filters-num:
  - 200
  - 200
  - 250
  - 250
  - 300
  - 300
  - 300
  - 300
char-conv-filters-widths:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
dropout-rnn: 0
dropout-src: 0
dropout-trg: 0
transformer-dropout: 0.1
transformer-dropout-attention: 0
transformer-dropout-ffn: 0
cost-type: ce-sum
multi-loss-type: sum
unlikelihood-loss: false
overwrite: true
no-reload: false
sentencepiece-alphas: []
sentencepiece-options: ""
sentencepiece-max-lines: 2000000
after-epochs: 0
after-batches: 0
after: 0e
disp-freq: 5000
disp-first: 10
disp-label-counts: true
save-freq: 2000
logical-epoch:
  - 1e
  - 0
max-length: 500
max-length-crop: false
tsv: false
tsv-fields: 0
shuffle: batches
no-restore-corpus: false
sqlite: ""
sqlite-drop: false
devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
num-devices: 0
no-nccl: false
#sharding: local
#sync-freq: 200u
cpu-threads: 0
mini-batch: 64
mini-batch-words: 0
mini-batch-fit: true
mini-batch-fit-step: 10
gradient-checkpointing: false
maxi-batch: 512
maxi-batch-sort: trg
shuffle-in-ram: false
data-threads: 8
all-caps-every: 0
english-title-case-every: 0
mini-batch-words-ref: 0
mini-batch-warmup: 0
mini-batch-track-lr: false
mini-batch-round-up: true
optimizer: adam
optimizer-params:
  - 0.92
  - 0.998
  - 1e-09
optimizer-delay: 10
sync-sgd: true
learn-rate: 0.0001
lr-report: true
lr-decay: 0
lr-decay-strategy: epoch+stalled
lr-decay-start:
  - 10
  - 1
lr-decay-freq: 50000
lr-decay-reset-optimizer: false
lr-decay-repeat-warmup: false
lr-decay-inv-sqrt:
  - 16000
lr-warmup: 16000
lr-warmup-start-rate: 0
lr-warmup-cycle: true
lr-warmup-at-reload: false
label-smoothing: 0.1
factor-weight: 1
clip-norm: 5
exponential-smoothing: 0.0001
guided-alignment: none
guided-alignment-cost: ce
guided-alignment-weight: 0.1
data-weighting: ""
data-weighting-type: sentence
embedding-vectors: []
embedding-normalization: false
embedding-fix-src: false
embedding-fix-trg: false
precision:
  - float16
  - float32
cost-scaling:
  - 8.f
  - 10000
  - 1.f
  - 8.f
gradient-norm-average-window: 100
dynamic-gradient-scaling: []
check-gradient-nan: false
normalize-gradient: false
train-embedder-rank: []
quantize-bits: 0
quantize-optimization-steps: 0
quantize-log-based: false
quantize-biases: false
ulr: false
ulr-query-vectors: ""
ulr-keys-vectors: ""
ulr-trainable-transformation: false
ulr-dim-emb: 0
ulr-dropout: 0
ulr-softmax-temperature: 1
valid-freq: 5000
valid-metrics:
  - chrf
  - bleu
  - perplexity
valid-reset-stalled: false
early-stopping: 10
early-stopping-on: first
beam-size: 6
normalize: 1
max-length-factor: 3
word-penalty: 0
allow-unk: true
n-best: false
word-scores: false
valid-mini-batch: 16
valid-max-length: 100
valid-script-path: ""
valid-script-args: []
valid-translation-output: ""
keep-best: true
