global:
  seed: 42
  src_lang: en
  tgt_lang: nn

  raw_data_dir: data/${.src_lang}-${.tgt_lang}/raw
  valid_dataset: flores200.dev

  opuscleaner_python_venv_dir: opuscleaner-venv
  opuscleaner_cmd: opuscleaner-clean

pipeline:
  pipeline_dir: experiments/${global.src_lang}-${global.tgt_lang}/opuscleaner-only.${global.src_lang}-${global.tgt_lang}
  steps:
    - step: raw
      step_label: raw.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.raw_data_dir}
    - step: clean
      step_label: clean.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      python_venv_dir: ${global.opuscleaner_python_venv_dir}
      previous_corpus_step: raw.${global.src_lang}-${global.tgt_lang}
  default_targets:
    - clean.${global.src_lang}-${global.tgt_lang}
