pipeline:
  pipeline_dir: experiments/${.langpair}/load_corpora.example

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}

  raw_data_dir: data/${.langpair}/raw
  valid_data_dir: data/${.langpair}/valid
  test_data_dir: data/${.langpair}/test

  steps:
    - step: raw
      step_label: raw.${pipeline.langpair}
    - step: raw
      step_label: valid.${pipeline.langpair}
      raw_data_dir: ${pipeline.valid_data_dir}
      compressed: false
    - step: raw
      step_label: test.${pipeline.langpair}
      raw_data_dir: ${pipeline.test_data_dir}
      compressed: false
  targets:
    - raw.${pipeline.langpair}
    - valid.${pipeline.langpair}
    - test.${pipeline.langpair}

runner:
  runner: bash
