global:
  seed: 42
  src_lang: en
  tgt_lang: nn

  # we set the "raw" data dir to the output of the preprocess pipeline
  raw_data_dir: experiments/${.src_lang}-${.tgt_lang}/preprocess.example/gather.${.src_lang}-${.tgt_lang}/output
  valid_data_dir: experiments/${.src_lang}-${.tgt_lang}/preprocess.example/valid.${.src_lang}-${.tgt_lang}/output
  test_data_dir: experiments/${.src_lang}-${.tgt_lang}/preprocess.example/test.${.src_lang}-${.tgt_lang}/output

  valid_dataset_prefix: flores200.dev

  decontaminate_min_length: 25

  marian_dir: marian_dir 
  marian_config: config/marian.train.teacher.base.yml

  vocab_size: 64000

pipeline:
  pipeline_dir: experiments/${global.src_lang}-${global.tgt_lang}/train.simple.example
  steps:
    # Load Datasets
    - step: raw
      step_label: gather.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.raw_data_dir}
    - step: raw
      step_label: valid.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.valid_data_dir}
    - step: raw
      step_label: test.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.test_data_dir}

    # Train
    - step: generate_vocab
      step_label: generate_vocab.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      datasets: 
        - clean.${global.src_lang}-${global.tgt_lang}
      marian_dir: ${global.marian_dir}
      corpus_step: gather.${global.src_lang}-${global.tgt_lang}
      vocab_size: ${global.vocab_size}
    - step: train_model
      step_label: train_model.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      marian_dir: ${global.marian_dir}
      marian_config: ${global.marian_config}
      opustrainer_config: null
      vocab_step: generate_vocab.${global.src_lang}-${global.tgt_lang}
      train_corpus_step: gather.${global.src_lang}-${global.tgt_lang}
      valid_corpus_step: valid.${global.src_lang}-${global.tgt_lang}
      valid_dataset: ${global.valid_dataset_prefix}.${global.src_lang}-${global.tgt_lang}
    - step: train_model
      step_label: train_model.${global.tgt_lang}-${global.src_lang}
      src_lang: ${global.tgt_lang}
      tgt_lang: ${global.src_lang}
      marian_dir: ${global.marian_dir}
      marian_config: ${global.marian_config}
      opustrainer_config: null
      vocab_step: generate_vocab.${global.src_lang}-${global.tgt_lang}
      train_corpus_step: gather.${global.src_lang}-${global.tgt_lang}
      valid_corpus_step: valid.${global.src_lang}-${global.tgt_lang}
      valid_dataset: ${global.valid_dataset_prefix}.${global.tgt_lang}-${global.src_lang}

  # Eval
  - step: translate
    step_label: translate_test.${global.src_lang}-${global.tgt_lang}
    src_lang: ${global.src_lang}
    tgt_lang: ${global.tgt_lang}
    previous_corpus_step: test.${global.src_lang}-${global.tgt_lang}
    model_step: train_model.${global.src_lang}-${global.tgt_lang}
    marian_dir: ${global.marian_dir}
  - step: evaluate
    step_label: evaluate_test.${global.src_lang}-${global.tgt_lang}
    src_lang: ${global.src_lang}
    tgt_lang: ${global.tgt_lang}
    previous_corpus_step: translate_test.${global.src_lang}-${global.tgt_lang}
    reference_corpus_step: test.${global.src_lang}-${global.tgt_lang}
  - step: translate
    step_label: translate_test.${global.tgt_lang}-${global.src_lang}
    src_lang: ${global.tgt_lang}
    tgt_lang: ${global.src_lang}
    previous_corpus_step: test.${global.src_lang}-${global.tgt_lang}
    model_step: train_model.${global.tgt_lang}-${global.src_lang}
    marian_dir: ${global.marian_dir}
  - step: evaluate
    step_label: evaluate_test.${global.tgt_lang}-${global.src_lang}
    src_lang: ${global.tgt_lang}
    tgt_lang: ${global.src_lang}
    previous_corpus_step: translate_test.${global.tgt_lang}-${global.src_lang}
    reference_corpus_step: test.${global.src_lang}-${global.tgt_lang}

  default_targets:
    - evaluate_test.${global.src_lang}-${global.tgt_lang}
    - evaluate_test.${global.tgt_lang}-${global.src_lang}
