pipeline:
  pipeline_dir: experiments/${.langpair}/preprocess.simple
  seed: 42

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}

  raw_para_dir: data/${.langpair}/raw
  # TODO: Replace the mono dirs with proper directories
  raw_mono_src_dir: data/${.langpair}/raw
  raw_mono_tgt_dir: data/${.langpair}/raw

  valid_data_dir: data/${.langpair}/valid
  test_data_dir: data/${.langpair}/test

  # this is required due to opustrainer and opuscleaner having conflicting dependencies
  python_venv_dir: opuscleaner-venv

  steps:
    # Load Datasets
    - step: raw
      step_label: raw.${pipeline.langpair}
      raw_data_dir: ${pipeline.raw_para_dir}
    - step: raw
      step_label: raw.${pipeline.src_lang}
      tgt_lang: null
      raw_data_dir: ${pipeline.raw_mono_src_dir}
    - step: raw
      step_label: raw.${pipeline.tgt_lang}
      src_lang: ${pipeline.tgt_lang}
      tgt_lang: null
      raw_data_dir: ${pipeline.raw_mono_tgt_dir}
    - step: raw
      step_label: valid.${pipeline.langpair}
      raw_data_dir: ${pipeline.valid_data_dir}
      compressed: false
    - step: raw
      step_label: test.${pipeline.langpair}
      raw_data_dir: ${pipeline.test_data_dir}
      compressed: false

    # Preprocessing
    - step: clean
      step_label: clean.${pipeline.langpair}
      prev_corpus_step: raw.${pipeline.langpair}
    - step: decontaminate
      step_label: decontaminate.${pipeline.langpair}
      prev_corpus_step: clean.${pipeline.langpair}
      valid_data_step: valid.${pipeline.langpair}
      test_data_step: test.${pipeline.langpair}
      min_length: 25
    - step: gather
      step_label: gather.${pipeline.langpair}
      prev_corpus_step: decontaminate.${pipeline.langpair}
    - step: gather
      step_label: gather.${pipeline.src_lang}
      src_lang: ${pipeline.src_lang}
      tgt_lang: null
      prev_corpus_step: raw.${pipeline.src_lang}
    - step: gather
      step_label: gather.${pipeline.tgt_lang}
      src_lang: ${pipeline.tgt_lang}
      tgt_lang: null
      prev_corpus_step: raw.${pipeline.tgt_lang}

  targets:
    - gather.${pipeline.langpair}
    - gather.${pipeline.src_lang}
    - gather.${pipeline.tgt_lang}
    - valid.${pipeline.langpair}
    - test.${pipeline.langpair}

runner:
  runner: bash
