seed: 42

#src_lang: en
#tgt_lang: eu
#raw_data_dir: "data/en-eu/raw/v0/para"
#valid_data_dir: "data/en-eu/valid"
#test_data_dir: "data/en-eu/test"

valid_dataset: "flores200.dev"

python_venv_dir: "venv"
marian_dir: "marian"

opuscleaner_cmd: "opuscleaner-clean"
decontaminate_path: "scripts/decontaminate.py"
marian_config: "config/marian.train.teacher.12x6.yml"
opustrainer_config: null

decontaminate_min_length: 25
vocab_size: 64000
