pipeline:
  pipeline_dir: experiments/${.langpair}/opuscleaner_only.example
  seed: 42

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}

  raw_data_dir: data/${.langpair}/raw

  # this is required due to opustrainer and opuscleaner having conflicting dependencies
  python_venv_dir: opuscleaner-venv
 
  steps:
    - step: raw
      step_label: raw.${pipeline.langpair}
    - step: clean
      step_label: clean.${pipeline.langpair}
      prev_corpus_step: raw.${pipeline.langpair}
  targets:
    - clean.${pipeline.langpair}

runner:
  runner: bash
