pipeline:
  pipeline_dir: experiments/${.langpair}/train.simple.example
  seed: 42

  src_lang: en
  tgt_lang: eu
  langpair: ${.src_lang}-${.tgt_lang}
  bt_langpair: ${.tgt_lang}-${.src_lang}

  preprocess_pipeline_dir: experiments/${.langpair}/preprocess.simple

  # We set the "raw" data dir to the output of the preprocess pipeline
  raw_data_dir: ${.preprocess_pipeline_dir}/gather.${.langpair}/output

  valid_data_dir: ${.preprocess_pipeline_dir}/valid.${.langpair}/output
  test_data_dir: ${.preprocess_pipeline_dir}/test.${.langpair}/output

  valid_dataset: flores200.dev.${.langpair}

  marian_dir: marian_dir 
  marian_config: config/marian.train.teacher.base.yml

  max_epochs: null
  vocab_size: 64000

  steps:
    # Load Datasets
    - step: raw
      step_label: gather.${pipeline.langpair}
      raw_data_dir: ${pipeline.raw_data_dir}
    - step: raw
      step_label: valid.${pipeline.langpair}
      raw_data_dir: ${pipeline.valid_data_dir}
    - step: raw
      step_label: test.${pipeline.langpair}
      raw_data_dir: ${pipeline.test_data_dir}

    # Train
    - step: generate_vocab
      step_label: generate_vocab.${pipeline.langpair}
      corpus_step: gather.${pipeline.langpair}
    - step: train_model
      step_label: train_model.${pipeline.langpair}
      opustrainer_config: null
      vocab_step: generate_vocab.${pipeline.langpair}
      train_corpus_step: gather.${pipeline.langpair}
      valid_corpus_step: valid.${pipeline.langpair}
      train_categories:
        - "clean"
      train_category_ratios:
        - 1.0
    - step: train_model
      step_label: train_model.${pipeline.bt_langpair}
      src_lang: ${pipeline.tgt_lang}
      tgt_lang: ${pipeline.src_lang}
      opustrainer_config: null
      vocab_step: generate_vocab.${pipeline.langpair}
      train_corpus_step: gather.${pipeline.langpair}
      valid_corpus_step: valid.${pipeline.langpair}
      train_categories:
        - "clean"
      train_category_ratios:
        - 1.0

    # Eval
    - step: translate
      step_label: translate_test.${pipeline.langpair}
      prev_corpus_step: test.${pipeline.langpair}
      model_step: train_model.${pipeline.langpair}
    - step: evaluate
      step_label: evaluate_test.${pipeline.langpair}
      translated_corpus_step: translate_test.${pipeline.langpair}
      reference_corpus_step: test.${pipeline.langpair}
    - step: translate
      step_label: translate_test.${pipeline.bt_langpair}
      src_lang: ${pipeline.tgt_lang}
      tgt_lang: ${pipeline.src_lang}
      prev_corpus_step: test.${pipeline.langpair}
      model_step: train_model.${pipeline.bt_langpair}
    - step: evaluate
      step_label: evaluate_test.${pipeline.bt_langpair}
      translated_corpus_step: translate_test.${pipeline.bt_langpair}
      reference_corpus_step: test.${pipeline.langpair}

  targets:
    - evaluate_test.${pipeline.langpair}
    - evaluate_test.${pipeline.bt_langpair}

runner:
  runner: bash
