global:
  src_lang: en
  tgt_lang: nn

  raw_data_dir: data/${.src_lang}-${.tgt_lang}/raw
  valid_data_dir: data/${.src_lang}-${.tgt_lang}/valid
  test_data_dir: data/${.src_lang}-${.tgt_lang}/test

pipeline:
  pipeline_dir: experiments/${global.src_lang}-${global.tgt_lang}/load_corpora.example
  steps:
    - step: raw
      step_label: raw.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.raw_data_dir}
    - step: raw
      step_label: valid.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.valid_data_dir}
      compressed: false
    - step: raw
      step_label: test.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.test_data_dir}
      compressed: false
  default_targets:
    - raw.${global.src_lang}-${global.tgt_lang}
    - valid.${global.src_lang}-${global.tgt_lang}
    - test.${global.src_lang}-${global.tgt_lang}
