global:
  seed: 42
  src_lang: en
  tgt_lang: nn

  raw_data_dir: data/${.src_lang}-${.tgt_lang}/raw
  valid_data_dir: data/${.src_lang}-${.tgt_lang}/valid
  test_data_dir: data/${.src_lang}-${.tgt_lang}/test
  valid_dataset: flores200.dev

  opuspocus_python_venv_dir: opuspocus-venv
  opuscleaner_python_venv_dir: opuscleaner-venv

  opuscleaner_cmd: opuscleaner-clean

  decontaminate_path: scripts/decontaminate.py
  decontaminate_min_length: 25

  marian_dir: marian_dir 
  marian_config: config/marian.train.teacher.base.yml

  vocab_size: 64000

pipeline:
  pipeline_dir: experiments/${global.src_lang}-${global.tgt_lang}/full.simple.${global.src_lang}-${global.tgt_lang}
  steps:
    # Preprocess
    - step: raw
      step_label: raw.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      raw_data_dir: ${global.raw_data_dir}
    - step: clean
      step_label: clean.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      python_venv_dir: ${global.opuscleaner_python_venv_dir}
      previous_corpus_step: raw.${global.src_lang}-${global.tgt_lang}
    - step: decontaminate
      step_label: decontaminate.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      previous_corpus_step: clean.${global.src_lang}-${global.tgt_lang}
      python_venv_dir: ${global.opuspocus_python_venv_dir}
      valid_data_dirs:
        - ${global.valid_data_dir}
        - ${global.test_data_dir}
      decontaminate_path: ${global.decontaminate_path}
      min_length: ${global.decontaminate_min_length}
    - step: gather
      step_label: gather.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      previous_corpus_step: decontaminate.${global.src_lang}-${global.tgt_lang}
      python_venv_dir: ${global.opuspocus_python_venv_dir}

    # Train
    - step: generate_vocab
      step_label: generate_vocab.${global.src_lang}-${global.tgt_lang}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      datasets: 
        - clean
      marian_dir: ${global.marian_dir}
      corpus_step: gather.${global.src_lang}-${global.tgt_lang}
      vocab_size: ${global.vocab_size}
    - step: train_model
      step_label: train_model.${global.src_lang}-${global.tgt_lang}
      marian_dir: ${global.marian_dir}
      valid_data_dir: ${global.valid_data_dir}
      python_venv_dir: ${global.opuspocus_python_venv_dir}
      src_lang: ${global.src_lang}
      tgt_lang: ${global.tgt_lang}
      marian_config: ${global.marian_config}
      opustrainer_config: null
      vocab_step: generate_vocab.${global.src_lang}-${global.tgt_lang}
      train_corpus_step: gather.${global.src_lang}-${global.tgt_lang}
    - step: train_model
      step_label: train_model.${global.tgt_lang}-${global.src_lang}
      marian_dir: ${global.marian_dir}
      valid_data_dir: ${global.valid_data_dir}
      python_venv_dir: ${global.opuspocus_python_venv_dir}
      src_lang: ${global.tgt_lang}
      tgt_lang: ${global.src_lang}
      marian_config: ${global.marian_config}
      opustrainer_config: null
      vocab_step: generate_vocab.${global.src_lang}-${global.tgt_lang}
      train_corpus_step: gather.${global.src_lang}-${global.tgt_lang}

  default_targets:
    - train_model.${global.src_lang}-${global.tgt_lang}
    - train_model.${global.tgt_lang}-${global.src_lang}
