#pipeline: iterative_backtranslation
seed: 42

#src_lang: en
#tgt_lang: eu
#raw_data_parallel_dir: "data/en-eu/raw/v0/para"
#raw_data_src_dir: "data/en-eu/raw/v0/en"
#raw_data_tgt_dir: ""data/en-eu/raw/v0/eu""
#valid_data_dir: "data/en-eu/valid"
#test_data_dir: "data/en-eu/test"

valid_dataset: "flores200.dev"

opuscleaner_cmd: "opuscleaner-clean"
decontaminate_path: "scripts/decontaminate.py"
marian_config: "config/marian.train.teacher.base.yml"
opustrainer_config: "config/opustrainer.teacher.base.yml"

decontaminate-min-length: 25
vocab_size: 64000
