seed: 42

#src_lang: en
#tgt_lang: eu
#raw_data_parallel_dir: "data/en-eu/raw/v0"
#raw_data_src_dir: "data/en/raw"
#raw_data_tgt_dir: "data/eu/raw"
#valid_data_dir: "data/en-eu/valid"
#test_data_dir: "data/en-eu/test"

valid_dataset: "flores200.dev"

skip_src_clean: True
skip_tgt_clean: True

python_venv_dir: "venv"
marian_dir: "marian"

opuscleaner_cmd: "opuscleaner-clean"
decontaminate_path: "scripts/decontaminate.py"
marian_config: "config/marian.train.teacher.12x12.yml"
opustrainer_config: null

decontaminate_min_length: 25
vocab_size: 64000
