name: Build and upload to PyPI

on:
  push:
  release:
    types:
      - published

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install
        run: python3 -m pip install .

      - name: Run runtime pytest
        run: pytest tests

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Set version number
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION = \"${GITHUB_REF_NAME:1}\"" > opuscleaner/__about__.py
      
      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/opuscleaner-*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Set version number
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION = \"${GITHUB_REF_NAME:1}\"" > opuscleaner/__about__.py
      
      - name: Build wheels
        run: python -m pip wheel -w wheelhouse .
      
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/opuscleaner-*.whl

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
